apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    blah: blah2
    traceId: 7679d822-20c5-477f-8463-e6db74b92e22\
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-app
        image: dangoldstein3/aquarium-create-namespace:0.0.3
        ports:
        - containerPort: 8080
