apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    hiroshi.dev/trace-id: c7fea81f-4856-47e5-8276-5f60a4d54fda
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 5
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: dangoldstein3/aquarium-create-namespace:0.0.3
          ports:
            - containerPort: 8080
