apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    hiroshi.dev/trace-id: c88b69c6-83c6-4615-823f-6f56dbeacc68
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 5
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: dangoldstein3/aquarium-create-namespace:0.0.3
          ports:
            - containerPort: 8080
