apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    hiroshi.dev/trace-id: ec87b583-8456-49e9-94d5-bad0fedb2b00
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 5
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: dangoldstein3/aquarium-create-namespace:0.0.3
          ports:
            - containerPort: 8080
