apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    hiroshi.dev/trace-id: 75537950-6735-47d0-b424-46e66d58372b
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 2
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: dangoldstein3/aquarium-create-namespace:0.0.3
          ports:
            - containerPort: 8080
