apiVersion: batch/v1
kind: Job
metadata:
  generateName: argo-postsync-notification-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argo-postsync-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"channel\": \"#somechannel\", \"username\": \"hello\", \"text\": \"App Sync succeeded\", \"icon_emoji\": \":ghost:\"}"
          - "https://90031d807357a17f00b04cdf356d1c4b.serveo.net"
      restartPolicy: Never
  backoffLimit: 2