apiVersion: batch/v1
kind: Job
metadata:
  generateName: example-app-presync-notification-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: example-app-presync-notification
          image: curlimages/curl
          command:
            - "curl"
            - "-X"
            - "POST"
            - "--json"
            - "{\"traceId\":\"ec87b583-8456-49e9-94d5-bad0fedb2b00\",\"status\":\"Started\"}"
            - "https://9f014d81fd21f5d69d95a57f743b7588.serveo.net/webhook/argocd"
      restartPolicy: Never
  backoffLimit: 2
