apiVersion: batch/v1
kind: Job
metadata:
  generateName: argo-presync-notification-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: argo-presync-notification
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "--data-urlencode"
          - "payload={\"status\": \"Started\", \"traceId\": \"7679d822-20c5-477f-8463-e6db74b92e22\"}"
          - "https://78629df81e5d6f61fd615a1e4231e628.serveo.net"
      restartPolicy: Never
  backoffLimit: 2