apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app-deployment
  labels:
    hiroshi.dev/trace-id: 37bb35b4-b6bc-4a61-a23c-274c740cfef9
spec:
  selector:
    matchLabels:
      app: example-app
  replicas: 1
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
        - name: example-app
          image: dangoldstein3/aquarium-create-namespace:0.0.3
          ports:
            - containerPort: 8080
