apiVersion: batch/v1
kind: Job
metadata:
  generateName: hello-world-presync-notification-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: hello-world-presync-notification
          image: curlimages/curl
          command:
            - curl
            - -X
            - POST
            - --json
            - {"traceId":"25632d7b-5726-4ca0-bd7b-b848ca627938","status":"Started"}
            - https://9f014d81fd21f5d69d95a57f743b7588.serveo.net/webhook/argocd
      restartPolicy: Never
  backoffLimit: 2
