apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: example-app
  namespace: argocd
spec:
  project: default
  source: 
    repoURL: https://github.com/ofekdeitch/argo-playground
    targetRevision: HEAD
    path: apps
    directory:
      recurse: true
  destination: 
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false

